server:
  servlet:
    encoding:
      enabled: 'true'
      force: 'true'
      charset: UTF-8
    context-path: /
  port: '9090'

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev

  datasource:
    password: ssafyA601
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: a601
    url: jdbc:mysql://localhost:3306/dnti?serverTimezone=UTC

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true